#include <iostream>
#include <string>

std::string generateList(int n);

int main(int argc, char *argv[])
{
    int default_value = 10;
    try {
        default_value = argc >= 2 ? std::stoi(argv[1]) : 10;
    } catch (const std::invalid_argument& e) {
        std::cout << argv[1] << " is an invalid number!" << std::endl;
        return 1;
    }
    std::string test = "A random string that is autogenerated";
    std::cout << generateList(default_value) << std::endl;

    return 0; 
}

std::string generateList(int n)
{
    std::string list = "[";
    for (int i = 0; i < n; i++)
    {
        list += std::to_string(i);
        if (i != n-1)
            list += ',';
    }
    list += "]";
    return list;
}

